### ISSUE TITLE
Nazar Butsenko,  sortirovki

### ISSUE THREAD

**Issue by Nazar173** [kotsolesya/algorithms-and-data-structures-2018#11]
![35497475-f47555fc-04d2-11e8-8c2f-06661044040b](https://user-images.githubusercontent.com/33486453/35580658-59e5ca0a-05f2-11e8-8b07-4b15e3e0005b.jpg)
kod -https://github.com/Nazar173/algoritm_2018/tree/master/Nazar(sort)

**Comment by kotsolesya** [comment]
Оцінка 4
