### ISSUE TITLE
Sula, sortirovka

### ISSUE THREAD

**Issue by VadymSula** [kotsolesya/algorithms-and-data-structures-2018#12]
sortirovka https://drive.google.com/drive/folders/1ofGR2WJurArH6l-CE5YD_RwTXz-VGdur
--tam i rezultat--

**Comment by kotsolesya** [comment]
Навіщо мені потрібно отримувати доступ до документу на google drive, якщо git якраз і є для того, щоб ділитися і зберігати код?

**Comment by VadymSula** [comment]
Вибачте, та через гіт мені на жаль не вдалося завантажити...


31 янв. 2018 г. 15:18 пользователь "Olesya" <notifications@github.com>
написал:

**Comment by kotsolesya** [comment]
Пройди курс
https://githowto.com/uk
