### ISSUE TITLE
Gorelik praktichnaya 2

### ISSUE THREAD

**Issue by ghost** [kotsolesya/algorithms-and-data-structures-2018#14]
https://github.com/EdwardUA/algorithms-and-data-structures-2018/tree/master/praktichna%202_Vnytrishnye%20sortyvanya

**Comment by kotsolesya** [comment]
ок

**Comment by artembocharov** [comment]
Bocharov toje delal postavte ocenky pjlst. On 'staralsya'.

**Comment by artembocharov** [comment]
Ny IIIo malchek tebe 3 z minusom.
