### ISSUE TITLE
Gorelik Praktichna 3, 4

### ISSUE THREAD

**Issue by ghost** [kotsolesya/algorithms-and-data-structures-2018#21]
https://github.com/EdwardUA/algorithms-and-data-structures-2018/tree/master/prakt%203
https://github.com/EdwardUA/algorithms-and-data-structures-2018/tree/master/prakt%204

**Comment by kotsolesya** [comment]
```
{ 
plosa[1]=603628;
Name[1]="Ukraine";
kontinent[1]="Europe";
city[1]="Kyiv";
naselenna[1]=42418235;

plosa[2]=409531;
Name[2]="OAE";
kontinent[2]="Azia";
city[2]="Aby-dabi";
naselenna[2]=5365215;
...
```
Це повинно бути у файлі, аж ніяк не в *.cpp

**Comment by kotsolesya** [comment]
4 не вся

**Comment by ghost** [comment]
Четвертая с доделанным вторым заданием
https://github.com/EdwardUA/algorithms-and-data-structures-2018/tree/master/praktichnaya%204%20vse%20zadaniya

**Comment by kotsolesya** [comment]
ок
