### ISSUE TITLE
Melnik : practical 5

### ISSUE THREAD

**Issue by amarsik1** [kotsolesya/algorithms-and-data-structures-2018#30]
kod - https://github.com/amarsik1/Algoritm_PS_2018/tree/master/pract5/pract5

**Comment by kotsolesya** [comment]
у тебе, один і той же код написсаний дуже багато разів - спрости

**Comment by amarsik1** [comment]
підкажіть будь ласка як можна це виправити?

**Comment by kotsolesya** [comment]
Замість значень у кейсах 63 - можна створити масив констант і по них проходитись
```
 case 63:
                     {
                         ifstream ip("priklad/63.csv");
```
а ще вираз "priklad/63.csv" - рядок, який можна створити із кількох рядків - подивись уважно що в тебе міняється і замість цього підстав змінну

**Comment by amarsik1** [comment]
як саме туди можна підставити змінну? в мене ніяк не виходило

**Comment by kotsolesya** [comment]
псевдокод:
`string filePath = "priklad/"+KOD+".csv";`
`+` заміни на функцію у С++ конкатенацію
KOD і є змінна за яку відповідає код оператора

**Comment by amarsik1** [comment]
та змінна повинна бути 'const char*' , і як мені тоді змінювати константу?

**Comment by kotsolesya** [comment]
ok
