### ISSUE TITLE
Practic work №3 (Andrienko)

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/algorithms-and-data-structures-2018#32]
![image](https://user-images.githubusercontent.com/26658198/36645000-11a35c48-1a6b-11e8-8980-d2a319bda345.png)
![image](https://user-images.githubusercontent.com/26658198/36645003-17d03294-1a6b-11e8-822b-7dddb8bed9a3.png)
![image](https://user-images.githubusercontent.com/26658198/36645017-419644e2-1a6b-11e8-8f2f-0a0f4a111df3.png)
https://github.com/Attiny2000/Practical-works/tree/master/Pract3

**Comment by kotsolesya** [comment]
ok
