### ISSUE TITLE
Pracktick Work # 3 - Svetlichniy Valeriy

### ISSUE THREAD

**Issue by Valeriy-Svetlichniy** [kotsolesya/algorithms-and-data-structures-2018#33]
https://github.com/VALLER1Y/algorithms-and-data-structures-2018/tree/master/Svetlichniy_Valeriy/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%96%203
![task_1](https://user-images.githubusercontent.com/32891528/36647648-9bb113fa-1a91-11e8-9ee8-df50d34ed830.png)
![task_2](https://user-images.githubusercontent.com/32891528/36647649-9bcbd834-1a91-11e8-92fc-0e31e8c14099.png)

**Comment by kotsolesya** [comment]
вірю, що в тебе вийде спростить код і попрацювати з файлом
