### ISSUE TITLE
Practic work №6 and №4 Andrienko

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/algorithms-and-data-structures-2018#34]
6 практическая
![image](https://user-images.githubusercontent.com/26658198/36656525-7ba590e6-1ad1-11e8-951d-c3a379ed2a9b.png)
https://github.com/Attiny2000/Practical-works/tree/master/Pract%206
и 4 практос
https://github.com/Attiny2000/Practical-works/tree/master/Pract4

**Comment by kotsolesya** [comment]
4 ok,
6 потрібно написати власну роботу зі стеком
