### ISSUE TITLE
Polish Сalculator - Svetlichniy Valeriy

### ISSUE THREAD

**Issue by Valeriy-Svetlichniy** [kotsolesya/algorithms-and-data-structures-2018#35]
https://github.com/VALLER1Y/algorithms-and-data-structures-2018/tree/master/Svetlichniy_Valeriy/%D0%9F%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9%20%D0%9A%D0%B0%D0%BB%D1%8C%D0%BA%D1%83%D0%BB%D1%8F%D1%82

**Comment by kotsolesya** [comment]
За goto буду наказувать
