### ISSUE TITLE
Самостоятельная работа(Андриенко)

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/algorithms-and-data-structures-2018#39]
https://github.com/Attiny2000/Practical-works/tree/master/OwnWork
Задание №1
![image](https://user-images.githubusercontent.com/26658198/36949433-014c4dd8-1ff1-11e8-8e36-4f54ab01d7fd.png)
![image](https://user-images.githubusercontent.com/26658198/36949460-5a25bc46-1ff1-11e8-9bcc-6db741fe818d.png)
Задание №2
![image](https://user-images.githubusercontent.com/26658198/36949814-1700dd10-1ff6-11e8-8716-827be43b0c47.png)

**Comment by kotsolesya** [comment]
ok
