### ISSUE TITLE
Svetlichniy Valeriy Practical Work # 1

### ISSUE THREAD

**Issue by Valeriy-Svetlichniy** [kotsolesya/algorithms-and-data-structures-2018#4]
Программа выполняет сортировки типа (Bubble, Instant, Select, Shell, Quick) на 100, 1000, 10000, 100000 элементов.

**Код :** https://github.com/VALLER1Y/algorithms-and-data-structures-2018/blob/master/Svetlichniy_Valeriy/Sort.cpp
![1](https://user-images.githubusercontent.com/32891528/35536319-385f0c3c-054f-11e8-9563-1cad8a14bf16.png)
![2](https://user-images.githubusercontent.com/32891528/35536320-388924ae-054f-11e8-85c6-35761769ae61.png)
![3](https://user-images.githubusercontent.com/32891528/35536328-3df603ee-054f-11e8-842b-07658013708b.png)
![4](https://user-images.githubusercontent.com/32891528/35536329-3e23c8ba-054f-11e8-8e96-aa3b47044cd0.png)

**Comment by kotsolesya** [comment]
щеб гарненько і компактно...
але зараховую
Оцінка 5
