### ISSUE TITLE
Home Work  (Bracket) - Svetlichniy Valeriy

### ISSUE THREAD

**Issue by Valeriy-Svetlichniy** [kotsolesya/algorithms-and-data-structures-2018#40]
https://github.com/VALLER1Y/algorithms-and-data-structures-2018/tree/master/Svetlichniy_Valeriy/Bracket
![2018-03-05 09-14-35](https://user-images.githubusercontent.com/32891528/36961860-d1604f1a-2055-11e8-885c-de27c4d24c72.png)

**Comment by kotsolesya** [comment]
ок
