### ISSUE TITLE
calculator and brackets

### ISSUE THREAD

**Issue by Dargon1999** [kotsolesya/algorithms-and-data-structures-2018#42]
https://github.com/YarmakOleksndr/OPtaAM_PS_2015/tree/master/Yarmosh_Oleksandr/PW%20%E2%84%966%20and%20brackets
+ D/Z
https://github.com/YarmakOleksndr/OPtaAM_PS_2015/tree/master/Yarmosh_Oleksandr/DZ

**Comment by kotsolesya** [comment]
а де ж реалізація стеку?
так можна було писать на 2 курсі ` stack[sp-2] = stack[sp-2] + stack[sp-1];`

**Comment by Dargon1999** [comment]
https://github.com/YarmakOleksndr/OPtaAM_PS_2015/blob/master/Yarmosh_Oleksandr/PW%20%E2%84%966%20and%20brackets/poland%20calculator.cpp

**Comment by kotsolesya** [comment]
ось звідки взято
https://github.com/amarsik1/Algoritm_PS_2018/blob/master/programs/%D0%BA%D0%B0%D0%BB%D1%8C%D0%BA%D1%83%D0%BB%D1%8F%D1%82%D0%BE%D1%80.cpp
це вже нахабство
