### ISSUE TITLE
13 03 18 dvosvyazniy spisok

### ISSUE THREAD

**Issue by ghost** [kotsolesya/algorithms-and-data-structures-2018#43]
https://github.com/EdwardUA/algorithms-and-data-structures-2018/blob/master/10%2003%2018%20spisok%20s%20dvoinoi%20svyazy/dvosvyazniy%20spisok%20bez%20komentov.txt

https://github.com/EdwardUA/algorithms-and-data-structures-2018/blob/master/10%2003%2018%20spisok%20s%20dvoinoi%20svyazy/sborsik.txt

Артему тоже щось поставте - він дуже-дуже старався.

**Comment by kotsolesya** [comment]
код у файлах `*.txt` не приймаю, навіщо тоді користуватися github?

**Comment by ghost** [comment]
https://github.com/EdwardUA/algorithms-and-data-structures-2018/tree/master/10%2003%2018%20spisok%20s%20dvoinoi%20svyazy/dvosvyazniy%20spisok/src

**Comment by kotsolesya** [comment]
в Run чомусь немає викликаних методів які описані в List
