### ISSUE TITLE
Proverte pjlst + S Artemom Bo4aRovim delal 

### ISSUE THREAD

**Issue by ghost** [kotsolesya/algorithms-and-data-structures-2018#6]
https://github.com/EdwardUA/algorithms-and-data-structures-2018

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/32891570/35497760-28f5eebc-04d4-11e8-8bbe-b9df866c9e56.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/32891570/35497829-86d24cce-04d4-11e8-873e-037ad711f2f7.png)

**Comment by kotsolesya** [comment]
ок
Обом оцінка
