### ISSUE TITLE
Ярмош Олександр ПР1 Sort

### ISSUE THREAD

**Issue by Dargon1999** [kotsolesya/algorithms-and-data-structures-2018#7]
https://github.com/YarmakOleksndr/OPtaAM_PS_2015/tree/master/Yarmosh_Oleksandr/Sorting
https://imgur.com/ftAxsQ2

**Comment by kotsolesya** [comment]
скинь нормально скрін роботи

**Comment by Dargon1999** [comment]
![image](https://user-images.githubusercontent.com/32891581/35502810-db3e70b4-04e6-11e8-9ddb-dfba5f2c245a.png)

**Comment by kotsolesya** [comment]
ок, 
Оцінка 5
