### ISSUE TITLE
Андриенко сортировки

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/algorithms-and-data-structures-2018#8]
https://github.com/Attiny2000/Sorting/blob/master/Program.cs
Все сортировки и время их выполнения
[et.xlsx](https://github.com/kotsolesya/algorithms-and-data-structures-2018/files/1672927/et.xlsx)

**Comment by kotsolesya** [comment]
продемонструй результат виконання, відповідно до таблиці, що була показана на парі

**Comment by Attiny2000** [comment]
![image](https://user-images.githubusercontent.com/26658198/35667198-6dc0e624-0735-11e8-864d-80be50b4aee2.png)
![image](https://user-images.githubusercontent.com/26658198/35667209-74be44e4-0735-11e8-9936-b83ae2e2787d.png)
![image](https://user-images.githubusercontent.com/26658198/35667225-80206362-0735-11e8-85f2-40e5c901a6fa.png)
![image](https://user-images.githubusercontent.com/26658198/35667243-975f1488-0735-11e8-83e3-9faa013d43ce.png)

**Comment by Attiny2000** [comment]
За что дизлайк? Что не так на этот раз? :(

**Comment by kotsolesya** [comment]
> відповідно до таблиці, що була показана на парі

**Comment by Attiny2000** [comment]
[et.xlsx](https://github.com/kotsolesya/algorithms-and-data-structures-2018/files/1693102/et.xlsx) вот таблица
