### ISSUE TITLE
Sugachenko Vadim Practical Work № 1

### ISSUE THREAD

**Issue by Vad1mka** [kotsolesya/algorithms-and-data-structures-2018#9]
Код: https://github.com/Vad1mka/Algorithm/blob/master/Sugachenko_Vadim/Sort.cpp

![image](https://user-images.githubusercontent.com/32891683/35518176-73d916d0-0519-11e8-8635-e97f9365c995.png)

**Comment by kotsolesya** [comment]
ок
5
